// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5O5-5az50CJQVn0Bb3ttRSNjmZR-LjoM',
    appId: '1:564881828108:web:2346acdb471b5fdd680129',
    messagingSenderId: '564881828108',
    projectId: 'noti-3b036',
    authDomain: 'noti-3b036.firebaseapp.com',
    storageBucket: 'noti-3b036.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ5x7MNmJkOhtq_UHgnH4fs-7nkzeanRU',
    appId: '1:564881828108:android:39374adfe00bb401680129',
    messagingSenderId: '564881828108',
    projectId: 'noti-3b036',
    storageBucket: 'noti-3b036.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI3-kC9INqZldgFrgERW911Y79dIZ3ye8',
    appId: '1:564881828108:ios:ac1a64ab6ea2bfae680129',
    messagingSenderId: '564881828108',
    projectId: 'noti-3b036',
    storageBucket: 'noti-3b036.appspot.com',
    iosClientId: '564881828108-4vfdqgpms5jmk57gnsrea4qjv8lbuj7b.apps.googleusercontent.com',
    iosBundleId: 'com.noti.app.noti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI3-kC9INqZldgFrgERW911Y79dIZ3ye8',
    appId: '1:564881828108:ios:ac1a64ab6ea2bfae680129',
    messagingSenderId: '564881828108',
    projectId: 'noti-3b036',
    storageBucket: 'noti-3b036.appspot.com',
    iosClientId: '564881828108-4vfdqgpms5jmk57gnsrea4qjv8lbuj7b.apps.googleusercontent.com',
    iosBundleId: 'com.noti.app.noti',
  );
}
